version: '3.8'

services:
  gemini-proxy:
    build: .
    container_name: gemini-proxy-service
    ports:
      - "8000:8000"
    restart: unless-stopped
    # 如果你还想通过环境变量自定义上游地址，可以在这里添加
    # environment:
      # - UPSTREAM_GEMINI_ENDPOINT=https://generativelanguage.googleapis.com